# author	: siham sharif
# date		: 31/Oct/2018
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Dockerfile for Oracle WebLogic Server 12.2.1.2 Generic Distro
#
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) fmw_12.2.1.2.0_wls_Disk1_1of1.zip
#     Download the Generic installer from http://www.oracle.com/technetwork/middleware/weblogic/downloads/wls-for-dev-1703574.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Dockerfile
# Run:
#      $ docker build -f Dockerfile.generic -t oracle/weblogic:12.2.1.2-generic .
#
# IMPORTANT
# ---------
# Pull base image and serverjre:8 image
# From the Oracle Registry
# -------------------------
FROM oracle/serverjre:8

# Maintainer
# ----------
MAINTAINER Siham Sharif <siham.sharif@gmail.com>

# Common environment variables required for this build (do NOT change)
# --------------------------------------------------------------------
ENV JAVA_HOME=/usr/local/jdk \
    MW=/usr/local/Oracle/Middleware/Oracle_Home \
    PATH=$PATH:$JAVA_HOME/bin:/usr/local/Oracle/Middleware/Oracle_Home/oracle_common/common/bin:/usr/local/Oracle/Middleware/Oracle_Home/OPatch

# Setup filesystem and oracle user
# Adjust file permissions, go to /usr/local/Oracle as user 'oracle' to proceed with WLS installation
# ------------------------------------------------------------
RUN useradd -d /usr/local/Oracle -m -s /bin/bash oracle && \
    mkdir -p /usr/local/Oracle/installerFiles && \
    chmod -R a+xr /usr/local/Oracle

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV FMW_PKG=fmw_12.2.1.2.0_wls_Disk1_1of1.zip \
    FMW_JAR=fmw_12.2.1.2.0_wls.jar

# Copy packages
# -------------
COPY $FMW_PKG install.rsp oraInst.loc /usr/local/Oracle/installerFiles/
RUN  chown -R oracle:oracle /usr/local/Oracle

# Install
# ------------------------------------------------------------
USER oracle

RUN cd /usr/local/Oracle/installerFiles && $JAVA_HOME/bin/jar xf /usr/local/Oracle/installerFiles/$FMW_PKG && cd - && \
    ls /usr/local/Oracle/installerFiles && \
    $JAVA_HOME/bin/java -jar /usr/local/Oracle/installerFiles/$FMW_JAR -silent -responseFile /usr/local/Oracle/installerFiles/install.rsp -invPtrLoc /usr/local/Oracle/installerFiles/oraInst.loc -novalidation && \
    rm -rf /usr/local/Oracle/installerFiles/*

WORKDIR /usr/local/Oracle
